#!/bin/bash

set -e

npm test

if [[ $TRAVIS_BRANCH == 'master' ]]; then

	rm -rf build || exit 0
	mkdir build
	./node_modules/gulp/bin/gulp.js build
	cd build

	git init

	git config user.name "travis"
	git config user.email "travis@travis-ci.org"

	git add .
	git commit -m "deploy to gh-pages"

	git push --force --quiet "https://${GH_TOKEN}@${GH_REPO}" master:gh-pages > /dev/null 2>&1

fi
